### ISSUE TITLE
Is the buml folder necessary?

### ISSUE THREAD

**Issue by dandelion-lowcode** [BESSER-PEARL/BESSER#121]
While trying the [DPP](https://besser.readthedocs.io/en/latest/examples/dpp.html) example, it strikes me as strange that the driver code generates a `buml` folder that is not really part of the solution. Both `buml_deployment_model` and `plantuml_to_buml` suffer from this, i.e.:

https://github.com/BESSER-PEARL/BESSER/blob/a3666cb97cab0f96993a46888ded3f44546f6a6e/besser/BUML/notations/structuralPlantUML/plantuml_to_buml.py#L24 

https://github.com/BESSER-PEARL/BESSER/blob/a3666cb97cab0f96993a46888ded3f44546f6a6e/besser/BUML/notations/deployment/buml_deployment.py#L24

Several proposals:

- Could some of them become pure functions (i.e., avoid writing to a file)?
- The destination folder could be exposed as a parameter, with `buml` as the default value
- Joining paths with `+ "/"` could break in Windows. Something like
  
  ```python
  os.path.join("buml", os.sep, buml_model_file_name + ".py")
  ```

  could be safer down the line.

**Comment by FitashUlHaq** [comment]
@dandelion-lowcode Thank you for the suggestions, we will update this in the next release.
