### ISSUE TITLE
Handle errors in OpenAI call

### ISSUE THREAD

**Issue by Aran30** [BESSER-PEARL/BESSER#75]
Due to limitations from OpenAI's API, images with a too large resolution will lead to an error. We should add an adequate error message for this kind of problem.

**Comment by FitashUlHaq** [comment]
I think we can handle this programmatically using PIL to increase usability of the tool :)

**Comment by Aran30** [comment]
After trying out some things, turns out the resolution is not the problem, but the used image has some weird problem. 
Opening the image with the paint application and pressing save solves the issue, so it does not seem to be a resolution problem. 
I'll add the image for good measure, but adding a warning message should be enough. 
![cursedImage](https://github.com/BESSER-PEARL/BESSER/assets/50965489/c94ee123-33bf-40d7-8b10-665be8fb6b09)

**Comment by ivan-alfonso** [comment]
Added error message in case of API problem.
